# workflow suggestion:
#   * ssh somewhere and start tmux
#   * 'prefix + t' to create a new window
#   * 'prefix + h' to move left amongst the windows
#   * 'prefix + l' to move right
#   * 'prefix + d' to detach
#   * 'tmux ls' to find the detached session
#   * 'tmux rename-session -t 0 myname' to rename a session
#   * 'tmux new-session' to start something new
#   * 'tmux attach -t name' to reattach
#   * 'prefix + Ctrl-s' to persist tmux sessions

# set a new tmux prefix: ctrl+g
set-option -g prefix C-g
unbind C-b

# vi-style movement amongst windows
unbind h
unbind l
bind h previous-window
bind l next-window

# 't' to create a new window
unbind t
bind t new-window

# change status bar appearance
set -g status-bg black
set -g status-fg white
set -g status-right "#[fg=grey]#H"

# use lotsa history
set -g history-limit 100000

# enable mouse scrolling
set -g mouse on

set -g default-shell /bin/zsh

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

# Add more programs to restart.
set -g @resurrect-processes '\
  "lvim" \
  "zola serve" \
  "npx wrangler dev" \
'

# Restore tmux sessions on reboot.
set -g @continuum-restore 'on'
set -g @continuum-boot-options 'iterm'

# Show pomodoro status.
set -g status-right "#{pomodoro_status}"

# Init plugin manager; keep at bottom of conf file.
run '~/.tmux/plugins/tpm/tpm'
